// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: enums.proto
// Protobuf C++ Version: 5.27.1

#include "enums.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace graphar {
namespace proto {
}  // namespace proto
}  // namespace graphar
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_enums_2eproto[3];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_enums_2eproto = nullptr;
const ::uint32_t TableStruct_enums_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;
const char descriptor_table_protodef_enums_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\013enums.proto\022\rgraphar.proto*z\n\010DataType"
    "\022\010\n\004BOOL\020\000\022\t\n\005INT32\020\001\022\t\n\005INT64\020\002\022\t\n\005FLOA"
    "T\020\003\022\n\n\006DOUBLE\020\004\022\n\n\006STRING\020\005\022\010\n\004LIST\020\006\022\010\n"
    "\004DATE\020\007\022\r\n\tTIMESTAMP\020\010\022\010\n\004TIME\020\t*G\n\010File"
    "Type\022\007\n\003CSV\020\000\022\013\n\007PARQUET\020\001\022\007\n\003ORC\020\002\022\010\n\004J"
    "SON\020\003\022\010\n\004AVRO\020\004\022\010\n\004HDF5\020\005*m\n\013AdjListType"
    "\022\027\n\023UNORDERED_BY_SOURCE\020\000\022\027\n\023UNORDERED_B"
    "Y_TARGET\020\001\022\025\n\021ORDERED_BY_SOURCE\020\002\022\025\n\021ORD"
    "ERED_BY_TARGET\020\003B\200\001\n\035org.apache.graphar."
    "info.protoB\nEnumsProtoP\001\242\002\003GPX\252\002\rGraphar"
    ".Proto\312\002\rGraphar\\Proto\342\002\031Graphar\\Proto\\G"
    "PBMetadata\352\002\016Graphar::Protob\006proto3"
};
static ::absl::once_flag descriptor_table_enums_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_enums_2eproto = {
    false,
    false,
    475,
    descriptor_table_protodef_enums_2eproto,
    "enums.proto",
    &descriptor_table_enums_2eproto_once,
    nullptr,
    0,
    0,
    schemas,
    file_default_instances,
    TableStruct_enums_2eproto::offsets,
    file_level_enum_descriptors_enums_2eproto,
    file_level_service_descriptors_enums_2eproto,
};
namespace graphar {
namespace proto {
const ::google::protobuf::EnumDescriptor* DataType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t DataType_internal_data_[] = {
    655360u, 0u, };
bool DataType_IsValid(int value) {
  return 0 <= value && value <= 9;
}
const ::google::protobuf::EnumDescriptor* FileType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[1];
}
PROTOBUF_CONSTINIT const uint32_t FileType_internal_data_[] = {
    393216u, 0u, };
bool FileType_IsValid(int value) {
  return 0 <= value && value <= 5;
}
const ::google::protobuf::EnumDescriptor* AdjListType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[2];
}
PROTOBUF_CONSTINIT const uint32_t AdjListType_internal_data_[] = {
    262144u, 0u, };
bool AdjListType_IsValid(int value) {
  return 0 <= value && value <= 3;
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace graphar
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_enums_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
