// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: vertex_info.proto
// Protobuf C++ Version: 5.27.1

#ifndef GOOGLE_PROTOBUF_INCLUDED_vertex_5finfo_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_vertex_5finfo_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5027001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "property_group.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_vertex_5finfo_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_vertex_5finfo_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_vertex_5finfo_2eproto;
namespace graphar {
namespace proto {
class VertexInfo;
struct VertexInfoDefaultTypeInternal;
extern VertexInfoDefaultTypeInternal _VertexInfo_default_instance_;
class VertexInfo_Statistics;
struct VertexInfo_StatisticsDefaultTypeInternal;
extern VertexInfo_StatisticsDefaultTypeInternal _VertexInfo_Statistics_default_instance_;
}  // namespace proto
}  // namespace graphar
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace graphar {
namespace proto {

// ===================================================================


// -------------------------------------------------------------------

class VertexInfo_Statistics final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:graphar.proto.VertexInfo.Statistics) */ {
 public:
  inline VertexInfo_Statistics() : VertexInfo_Statistics(nullptr) {}
  ~VertexInfo_Statistics() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR VertexInfo_Statistics(
      ::google::protobuf::internal::ConstantInitialized);

  inline VertexInfo_Statistics(const VertexInfo_Statistics& from) : VertexInfo_Statistics(nullptr, from) {}
  inline VertexInfo_Statistics(VertexInfo_Statistics&& from) noexcept
      : VertexInfo_Statistics(nullptr, std::move(from)) {}
  inline VertexInfo_Statistics& operator=(const VertexInfo_Statistics& from) {
    CopyFrom(from);
    return *this;
  }
  inline VertexInfo_Statistics& operator=(VertexInfo_Statistics&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const VertexInfo_Statistics& default_instance() {
    return *internal_default_instance();
  }
  static inline const VertexInfo_Statistics* internal_default_instance() {
    return reinterpret_cast<const VertexInfo_Statistics*>(
        &_VertexInfo_Statistics_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(VertexInfo_Statistics& a, VertexInfo_Statistics& b) { a.Swap(&b); }
  inline void Swap(VertexInfo_Statistics* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VertexInfo_Statistics* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  VertexInfo_Statistics* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<VertexInfo_Statistics>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const VertexInfo_Statistics& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const VertexInfo_Statistics& from) { VertexInfo_Statistics::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(VertexInfo_Statistics* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "graphar.proto.VertexInfo.Statistics"; }

 protected:
  explicit VertexInfo_Statistics(::google::protobuf::Arena* arena);
  VertexInfo_Statistics(::google::protobuf::Arena* arena, const VertexInfo_Statistics& from);
  VertexInfo_Statistics(::google::protobuf::Arena* arena, VertexInfo_Statistics&& from) noexcept
      : VertexInfo_Statistics(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNumVerticesFieldNumber = 1,
    kNumChunksFieldNumber = 2,
  };
  // int64 num_vertices = 1 [json_name = "numVertices"];
  void clear_num_vertices() ;
  ::int64_t num_vertices() const;
  void set_num_vertices(::int64_t value);

  private:
  ::int64_t _internal_num_vertices() const;
  void _internal_set_num_vertices(::int64_t value);

  public:
  // int64 num_chunks = 2 [json_name = "numChunks"];
  void clear_num_chunks() ;
  ::int64_t num_chunks() const;
  void set_num_chunks(::int64_t value);

  private:
  ::int64_t _internal_num_chunks() const;
  void _internal_set_num_chunks(::int64_t value);

  public:
  // @@protoc_insertion_point(class_scope:graphar.proto.VertexInfo.Statistics)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_VertexInfo_Statistics_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const VertexInfo_Statistics& from_msg);
    ::int64_t num_vertices_;
    ::int64_t num_chunks_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_vertex_5finfo_2eproto;
};
// -------------------------------------------------------------------

class VertexInfo final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:graphar.proto.VertexInfo) */ {
 public:
  inline VertexInfo() : VertexInfo(nullptr) {}
  ~VertexInfo() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR VertexInfo(
      ::google::protobuf::internal::ConstantInitialized);

  inline VertexInfo(const VertexInfo& from) : VertexInfo(nullptr, from) {}
  inline VertexInfo(VertexInfo&& from) noexcept
      : VertexInfo(nullptr, std::move(from)) {}
  inline VertexInfo& operator=(const VertexInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline VertexInfo& operator=(VertexInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const VertexInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const VertexInfo* internal_default_instance() {
    return reinterpret_cast<const VertexInfo*>(
        &_VertexInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(VertexInfo& a, VertexInfo& b) { a.Swap(&b); }
  inline void Swap(VertexInfo* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VertexInfo* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  VertexInfo* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<VertexInfo>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const VertexInfo& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const VertexInfo& from) { VertexInfo::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(VertexInfo* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "graphar.proto.VertexInfo"; }

 protected:
  explicit VertexInfo(::google::protobuf::Arena* arena);
  VertexInfo(::google::protobuf::Arena* arena, const VertexInfo& from);
  VertexInfo(::google::protobuf::Arena* arena, VertexInfo&& from) noexcept
      : VertexInfo(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using Statistics = VertexInfo_Statistics;

  // accessors -------------------------------------------------------
  enum : int {
    kPropertiesFieldNumber = 3,
    kTypeFieldNumber = 1,
    kPrefixFieldNumber = 4,
    kStatisticsFieldNumber = 5,
    kChunkSizeFieldNumber = 2,
  };
  // repeated .graphar.proto.PropertyGroup properties = 3 [json_name = "properties"];
  int properties_size() const;
  private:
  int _internal_properties_size() const;

  public:
  void clear_properties() ;
  ::graphar::proto::PropertyGroup* mutable_properties(int index);
  ::google::protobuf::RepeatedPtrField<::graphar::proto::PropertyGroup>* mutable_properties();

  private:
  const ::google::protobuf::RepeatedPtrField<::graphar::proto::PropertyGroup>& _internal_properties() const;
  ::google::protobuf::RepeatedPtrField<::graphar::proto::PropertyGroup>* _internal_mutable_properties();
  public:
  const ::graphar::proto::PropertyGroup& properties(int index) const;
  ::graphar::proto::PropertyGroup* add_properties();
  const ::google::protobuf::RepeatedPtrField<::graphar::proto::PropertyGroup>& properties() const;
  // string type = 1 [json_name = "type"];
  void clear_type() ;
  const std::string& type() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_type(Arg_&& arg, Args_... args);
  std::string* mutable_type();
  PROTOBUF_NODISCARD std::string* release_type();
  void set_allocated_type(std::string* value);

  private:
  const std::string& _internal_type() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_type(
      const std::string& value);
  std::string* _internal_mutable_type();

  public:
  // string prefix = 4 [json_name = "prefix"];
  void clear_prefix() ;
  const std::string& prefix() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_prefix(Arg_&& arg, Args_... args);
  std::string* mutable_prefix();
  PROTOBUF_NODISCARD std::string* release_prefix();
  void set_allocated_prefix(std::string* value);

  private:
  const std::string& _internal_prefix() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_prefix(
      const std::string& value);
  std::string* _internal_mutable_prefix();

  public:
  // optional .graphar.proto.VertexInfo.Statistics statistics = 5 [json_name = "statistics"];
  bool has_statistics() const;
  void clear_statistics() ;
  const ::graphar::proto::VertexInfo_Statistics& statistics() const;
  PROTOBUF_NODISCARD ::graphar::proto::VertexInfo_Statistics* release_statistics();
  ::graphar::proto::VertexInfo_Statistics* mutable_statistics();
  void set_allocated_statistics(::graphar::proto::VertexInfo_Statistics* value);
  void unsafe_arena_set_allocated_statistics(::graphar::proto::VertexInfo_Statistics* value);
  ::graphar::proto::VertexInfo_Statistics* unsafe_arena_release_statistics();

  private:
  const ::graphar::proto::VertexInfo_Statistics& _internal_statistics() const;
  ::graphar::proto::VertexInfo_Statistics* _internal_mutable_statistics();

  public:
  // int64 chunk_size = 2 [json_name = "chunkSize"];
  void clear_chunk_size() ;
  ::int64_t chunk_size() const;
  void set_chunk_size(::int64_t value);

  private:
  ::int64_t _internal_chunk_size() const;
  void _internal_set_chunk_size(::int64_t value);

  public:
  // @@protoc_insertion_point(class_scope:graphar.proto.VertexInfo)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 5, 2,
      43, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_VertexInfo_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const VertexInfo& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::graphar::proto::PropertyGroup > properties_;
    ::google::protobuf::internal::ArenaStringPtr type_;
    ::google::protobuf::internal::ArenaStringPtr prefix_;
    ::graphar::proto::VertexInfo_Statistics* statistics_;
    ::int64_t chunk_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_vertex_5finfo_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// VertexInfo_Statistics

// int64 num_vertices = 1 [json_name = "numVertices"];
inline void VertexInfo_Statistics::clear_num_vertices() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.num_vertices_ = ::int64_t{0};
}
inline ::int64_t VertexInfo_Statistics::num_vertices() const {
  // @@protoc_insertion_point(field_get:graphar.proto.VertexInfo.Statistics.num_vertices)
  return _internal_num_vertices();
}
inline void VertexInfo_Statistics::set_num_vertices(::int64_t value) {
  _internal_set_num_vertices(value);
  // @@protoc_insertion_point(field_set:graphar.proto.VertexInfo.Statistics.num_vertices)
}
inline ::int64_t VertexInfo_Statistics::_internal_num_vertices() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.num_vertices_;
}
inline void VertexInfo_Statistics::_internal_set_num_vertices(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.num_vertices_ = value;
}

// int64 num_chunks = 2 [json_name = "numChunks"];
inline void VertexInfo_Statistics::clear_num_chunks() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.num_chunks_ = ::int64_t{0};
}
inline ::int64_t VertexInfo_Statistics::num_chunks() const {
  // @@protoc_insertion_point(field_get:graphar.proto.VertexInfo.Statistics.num_chunks)
  return _internal_num_chunks();
}
inline void VertexInfo_Statistics::set_num_chunks(::int64_t value) {
  _internal_set_num_chunks(value);
  // @@protoc_insertion_point(field_set:graphar.proto.VertexInfo.Statistics.num_chunks)
}
inline ::int64_t VertexInfo_Statistics::_internal_num_chunks() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.num_chunks_;
}
inline void VertexInfo_Statistics::_internal_set_num_chunks(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.num_chunks_ = value;
}

// -------------------------------------------------------------------

// VertexInfo

// string type = 1 [json_name = "type"];
inline void VertexInfo::clear_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_.ClearToEmpty();
}
inline const std::string& VertexInfo::type() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:graphar.proto.VertexInfo.type)
  return _internal_type();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void VertexInfo::set_type(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:graphar.proto.VertexInfo.type)
}
inline std::string* VertexInfo::mutable_type() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_type();
  // @@protoc_insertion_point(field_mutable:graphar.proto.VertexInfo.type)
  return _s;
}
inline const std::string& VertexInfo::_internal_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.type_.Get();
}
inline void VertexInfo::_internal_set_type(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_.Set(value, GetArena());
}
inline std::string* VertexInfo::_internal_mutable_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.type_.Mutable( GetArena());
}
inline std::string* VertexInfo::release_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:graphar.proto.VertexInfo.type)
  return _impl_.type_.Release();
}
inline void VertexInfo::set_allocated_type(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.type_.IsDefault()) {
          _impl_.type_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:graphar.proto.VertexInfo.type)
}

// int64 chunk_size = 2 [json_name = "chunkSize"];
inline void VertexInfo::clear_chunk_size() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.chunk_size_ = ::int64_t{0};
}
inline ::int64_t VertexInfo::chunk_size() const {
  // @@protoc_insertion_point(field_get:graphar.proto.VertexInfo.chunk_size)
  return _internal_chunk_size();
}
inline void VertexInfo::set_chunk_size(::int64_t value) {
  _internal_set_chunk_size(value);
  // @@protoc_insertion_point(field_set:graphar.proto.VertexInfo.chunk_size)
}
inline ::int64_t VertexInfo::_internal_chunk_size() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.chunk_size_;
}
inline void VertexInfo::_internal_set_chunk_size(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.chunk_size_ = value;
}

// repeated .graphar.proto.PropertyGroup properties = 3 [json_name = "properties"];
inline int VertexInfo::_internal_properties_size() const {
  return _internal_properties().size();
}
inline int VertexInfo::properties_size() const {
  return _internal_properties_size();
}
inline ::graphar::proto::PropertyGroup* VertexInfo::mutable_properties(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:graphar.proto.VertexInfo.properties)
  return _internal_mutable_properties()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::graphar::proto::PropertyGroup>* VertexInfo::mutable_properties()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:graphar.proto.VertexInfo.properties)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_properties();
}
inline const ::graphar::proto::PropertyGroup& VertexInfo::properties(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:graphar.proto.VertexInfo.properties)
  return _internal_properties().Get(index);
}
inline ::graphar::proto::PropertyGroup* VertexInfo::add_properties() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::graphar::proto::PropertyGroup* _add = _internal_mutable_properties()->Add();
  // @@protoc_insertion_point(field_add:graphar.proto.VertexInfo.properties)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::graphar::proto::PropertyGroup>& VertexInfo::properties() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:graphar.proto.VertexInfo.properties)
  return _internal_properties();
}
inline const ::google::protobuf::RepeatedPtrField<::graphar::proto::PropertyGroup>&
VertexInfo::_internal_properties() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.properties_;
}
inline ::google::protobuf::RepeatedPtrField<::graphar::proto::PropertyGroup>*
VertexInfo::_internal_mutable_properties() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.properties_;
}

// string prefix = 4 [json_name = "prefix"];
inline void VertexInfo::clear_prefix() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.prefix_.ClearToEmpty();
}
inline const std::string& VertexInfo::prefix() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:graphar.proto.VertexInfo.prefix)
  return _internal_prefix();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void VertexInfo::set_prefix(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.prefix_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:graphar.proto.VertexInfo.prefix)
}
inline std::string* VertexInfo::mutable_prefix() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_prefix();
  // @@protoc_insertion_point(field_mutable:graphar.proto.VertexInfo.prefix)
  return _s;
}
inline const std::string& VertexInfo::_internal_prefix() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.prefix_.Get();
}
inline void VertexInfo::_internal_set_prefix(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.prefix_.Set(value, GetArena());
}
inline std::string* VertexInfo::_internal_mutable_prefix() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.prefix_.Mutable( GetArena());
}
inline std::string* VertexInfo::release_prefix() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:graphar.proto.VertexInfo.prefix)
  return _impl_.prefix_.Release();
}
inline void VertexInfo::set_allocated_prefix(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.prefix_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.prefix_.IsDefault()) {
          _impl_.prefix_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:graphar.proto.VertexInfo.prefix)
}

// optional .graphar.proto.VertexInfo.Statistics statistics = 5 [json_name = "statistics"];
inline bool VertexInfo::has_statistics() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.statistics_ != nullptr);
  return value;
}
inline void VertexInfo::clear_statistics() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.statistics_ != nullptr) _impl_.statistics_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::graphar::proto::VertexInfo_Statistics& VertexInfo::_internal_statistics() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::graphar::proto::VertexInfo_Statistics* p = _impl_.statistics_;
  return p != nullptr ? *p : reinterpret_cast<const ::graphar::proto::VertexInfo_Statistics&>(::graphar::proto::_VertexInfo_Statistics_default_instance_);
}
inline const ::graphar::proto::VertexInfo_Statistics& VertexInfo::statistics() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:graphar.proto.VertexInfo.statistics)
  return _internal_statistics();
}
inline void VertexInfo::unsafe_arena_set_allocated_statistics(::graphar::proto::VertexInfo_Statistics* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.statistics_);
  }
  _impl_.statistics_ = reinterpret_cast<::graphar::proto::VertexInfo_Statistics*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:graphar.proto.VertexInfo.statistics)
}
inline ::graphar::proto::VertexInfo_Statistics* VertexInfo::release_statistics() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::graphar::proto::VertexInfo_Statistics* released = _impl_.statistics_;
  _impl_.statistics_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::graphar::proto::VertexInfo_Statistics* VertexInfo::unsafe_arena_release_statistics() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:graphar.proto.VertexInfo.statistics)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::graphar::proto::VertexInfo_Statistics* temp = _impl_.statistics_;
  _impl_.statistics_ = nullptr;
  return temp;
}
inline ::graphar::proto::VertexInfo_Statistics* VertexInfo::_internal_mutable_statistics() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.statistics_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::graphar::proto::VertexInfo_Statistics>(GetArena());
    _impl_.statistics_ = reinterpret_cast<::graphar::proto::VertexInfo_Statistics*>(p);
  }
  return _impl_.statistics_;
}
inline ::graphar::proto::VertexInfo_Statistics* VertexInfo::mutable_statistics() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::graphar::proto::VertexInfo_Statistics* _msg = _internal_mutable_statistics();
  // @@protoc_insertion_point(field_mutable:graphar.proto.VertexInfo.statistics)
  return _msg;
}
inline void VertexInfo::set_allocated_statistics(::graphar::proto::VertexInfo_Statistics* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete (_impl_.statistics_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = (value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.statistics_ = reinterpret_cast<::graphar::proto::VertexInfo_Statistics*>(value);
  // @@protoc_insertion_point(field_set_allocated:graphar.proto.VertexInfo.statistics)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace graphar


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_vertex_5finfo_2eproto_2epb_2eh
