# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# See: https://cwiki.apache.org/confluence/display/INFRA/git+-+.asf.yaml+features

github:
  description: An open source, standard data file format for graph data storage and retrieval.
  homepage: https://graphar.apache.org/
  labels:
    - big-data
    - graph
    - etl
    - spark
    - pyspark
    - graph-analysis
    - data-orchestration
    - graph-storage
  enabled_merge_buttons:
    squash: true
    merge: false
    rebase: false
  protected_branches:
    main:
      required_status_checks:
        strict: false
      required_pull_request_reviews:
        dismiss_stale_reviews: false
        required_approving_review_count: 1
      required_linear_history: true
  features:
    issues: true
    discussions: true
    wiki: true
    projects: true
notifications:
  commits: commits@graphar.apache.org
  issues: commits@graphar.apache.org
  pullrequests: commits@graphar.apache.org
  jobs:         commits@graphar.apache.org
  discussions:  commits@graphar.apache.org

