cmake -DCMAKE_BUILD_TYPE=Release -DARROW_BUILD_TESTS=OFF -DARROW_CSV=ON -DARROW_PARQUET=ON -DARROW_DATASET=ON -DARROW_BUILD_EXAMPLES=ON -DARROW_FILESYSTEM=ON -DPARQUET_BUILD_EXAMPLES=ON ../encoding/cpp
make -j4
