#!/bin/bash
echo 'cont1_l'
# Download: https://networkrepository.com/cont1-l.php
./Csv2Parquet /mnt/dataset/cont1-l/cont1_l_full.mtx /root/dataset/cont1_l 2
./data-generator /mnt/dataset/cont1-l/cont1_l_full.mtx /root/dataset/cont1_l 1921597 false true false true space 2
./decode-bit-map /root/dataset/cont1_l 1921597 1921596 delta
./decode-bit-map /root/dataset/cont1_l 1921597 1921596 base
./decode-bit-map /root/dataset/cont1_l 1921597 1921596

echo 'degme'
# Download: https://networkrepository.com/degme.php
./Csv2Parquet /mnt/dataset/degme/degme_full.mtx /root/dataset/degme 2
./data-generator /mnt/dataset/degme/degme_full.mtx /root/dataset/degme 659416 false true false false space 2
./decode-bit-map /root/dataset/degme 659416 185501 delta
./decode-bit-map /root/dataset/degme 659416 185501 base
./decode-bit-map /root/dataset/degme 659416 185501

echo 'tp-6'
# Download: https://networkrepository.com/tp-6.php
./Csv2Parquet /mnt/dataset/tp-6/tp-6_full.mtx /root/dataset/tp-6 0
./data-generator /mnt/dataset/tp-6/tp-6.mtx /root/dataset/tp-6 1100000 true true false false space 0
./decode-bit-map /root/dataset/tp-6 1100000 6073 delta
./decode-bit-map /root/dataset/tp-6 1100000 6073 base
./decode-bit-map /root/dataset/tp-6 1100000 6073

echo 'hollywood-2009'
# Download: https://www.cise.ufl.edu/research/sparse/MM/LAW/hollywood-2009.tar.gz
./Csv2Parquet /mnt/dataset/hollywood-2009/hollywood-2009.mtx /root/dataset/hollywood-2009 1
./data-generator /mnt/dataset/hollywood-2009/hollywood-2009.mtx /root/dataset/hollywood-2009 1139906 false true false false space 1
./decode-bit-map /root/dataset/hollywood-2009 1139906 601226 delta
./decode-bit-map /root/dataset/hollywood-2009 1139906 601226 base
./decode-bit-map /root/dataset/hollywood-2009 1139906 601226

echo 'indochina-2004'
# Download: https://www.cise.ufl.edu/research/sparse/MM/LAW/indochina-2004.tar.gz
./Csv2Parquet /mnt/dataset/indochina-2004/indochina-2004.mtx /root/dataset/indochina-2004 1
./data-generator /mnt/dataset/indochina-2004/indochina-2004.mtx /root/dataset/indochina-2004 7414867 false true false false space 1
./decode-bit-map /root/dataset/indochina-2004 7414867 7030320 delta
./decode-bit-map /root/dataset/indochina-2004 7414867 7030320 base
./decode-bit-map /root/dataset/indochina-2004 7414867 7030320

echo 'wiki'
# Download: http://konect.cc/networks/wikipedia_link_en/
./Csv2Parquet /mnt/dataset/wiki/wikipedia_link_en/out.wikipedia_link_en /root/dataset/wiki 1
./data-generator /mnt/dataset/wiki/wikipedia_link_en/out.wikipedia_link_en /root/dataset/wiki 13593032 false false false true tab 1
./decode-bit-map /root/dataset/wiki 13593032 134151 delta
./decode-bit-map /root/dataset/wiki 13593032 134151 base
./decode-bit-map /root/dataset/wiki 13593032 134151

echo 'uk-2002'
# Download: https://www.cise.ufl.edu/research/sparse/MM/LAW/uk-2002.tar.gz
./Csv2Parquet /mnt/dataset/uk-2002/uk-2002.mtx /root/dataset/uk-2002 1
./data-generator /mnt/dataset/uk-2002/uk-2002.mtx /root/dataset/uk-2002 18520486 false true false false space 1
./decode-bit-map /root/dataset/uk-2002 18520486 17159800 delta 
./decode-bit-map /root/dataset/uk-2002 18520486 17159800 base
./decode-bit-map /root/dataset/uk-2002 18520486 17159800

echo 'arabic-2005'
# Download: https://www.cise.ufl.edu/research/sparse/MM/LAW/arabic-2005.tar.gz
./Csv2Parquet /mnt/dataset/arabic-2005/arabic-2005.mtx /root/dataset/arabic-2005 1
./data-generator /mnt/dataset/arabic-2005/arabic-2005.mtx /root/dataset/arabic-2005 22744081 false true false false space 1
./decode-bit-map /root/dataset/arabic-2005 22744081 13720651 delta
./decode-bit-map /root/dataset/arabic-2005 22744081 13720651 base
./decode-bit-map /root/dataset/arabic-2005 22744081 13720651

echo 'uk-2005'
# Download: https://www.cise.ufl.edu/research/sparse/MM/LAW/uk-2005.tar.gz
./Csv2Parquet /mnt/dataset/uk-2005/uk-2005.mtx /root/dataset/uk-2005 1
./data-generator /mnt/dataset/uk-2005/uk-2005.mtx /root/dataset/uk-2005 39459926 false true false false space 1
./decode-bit-map /root/dataset/uk-2005 39459926 34054381 delta 
./decode-bit-map /root/dataset/uk-2005 39459926 34054381 base
./decode-bit-map /root/dataset/uk-2005 39459926 34054381

echo 'webbase-2001'
# Download: https://www.cise.ufl.edu/research/sparse/MM/LAW/webbase-2001.tar.gz
./Csv2Parquet /mnt/dataset/webbase-2001/webbase-2001.mtx /root/dataset/webbase-2001 1
./data-generator /mnt/dataset/webbase-2001/webbase-2001.mtx /root/dataset/webbase-2001 118142156 false true false false space 1
./decode-bit-map /root/dataset/webbase-2001 118142156 111342910 delta
./decode-bit-map /root/dataset/webbase-2001 118142156 111342910 base
./decode-bit-map /root/dataset/webbase-2001 118142156 111342910

echo 'graph500-28'
# Generated by Graph500 generator (https://graph500.org/), scale 28
./Csv2Parquet /mnt/dataset/graph500/graph500-28.e /root/dataset/graph500-28 0
./data-generator /mnt/dataset/graph500/graph500-28.e /root/dataset/graph500-28 268432759 true false false false space 0
./decode-bit-map /root/dataset/graph500-28 268432759 798169 delta
./decode-bit-map /root/dataset/graph500-28 268432759 798169 base
./decode-bit-map /root/dataset/graph500-28 268432759 798169

echo 'graph500-29'
# Generated by Graph500 generator (https://graph500.org/), scale 29
./Csv2Parquet /mnt/dataset/graph500/graph500-29.e /root/dataset/graph500-29 0
./data-generator /mnt/dataset/graph500/graph500-29.e /root/dataset/graph500-29 536864624 true false false false space 0
./decode-bit-map /root/dataset/graph500-29 536864624 231765318 delta
./decode-bit-map /root/dataset/graph500-29 536864624 231765318 base
./decode-bit-map /root/dataset/graph500-29 536864624 231765318

echo 'synthetic-5'
# Generated by synthetic generator, 75,000,000 vertices
./Csv2Parquet /mnt/dataset/synthetic/synthetic-5 /root/dataset/synthetic-5 0
./data-generator /mnt/dataset/synthetic/synthetic-5 /root/dataset/synthetic-5 75000000 true false true false space 0
./decode-bit-map /root/dataset/synthetic-5 75000000 51446597 delta
./decode-bit-map /root/dataset/synthetic-5 75000000 51446597 base
./decode-bit-map /root/dataset/synthetic-5 75000000 51446597

echo 'synthetic-7'
# Generated by synthetic generator, 100,000,000 vertices
./Csv2Parquet /mnt/dataset/synthetic/synthetic-7 /root/dataset/synthetic-7 0
./data-generator /mnt/dataset/synthetic/synthetic-7 /root/dataset/synthetic-7 100000000 true false true false space 0
./decode-bit-map /root/dataset/synthetic-7 100000000 47432856 delta
./decode-bit-map /root/dataset/synthetic-7 100000000 47432856 base
./decode-bit-map /root/dataset/synthetic-7 100000000 47432856
