# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

from __future__ import annotations

try:
    # Generated by setuptools-scm at build time (see [tool.setuptools_scm]).
    from ._version import __version__
except ImportError:  # source tree without a build
    __version__ = "0.0.0"

# Importing names through the submodules also makes the submodules themselves
# available as attributes (e.g. graphar.graph_info), which tests rely on.
from .graph_info import (
    AdjacentList,
    DataType,
    EdgeInfo,
    GraphInfo,
    Property,
    PropertyGroup,
    VertexInfo,
)
from .high_level import (
    BuilderEdge,
    BuilderVertex,
    Edge,
    EdgeIter,
    EdgesBuilder,
    EdgesCollection,
    Vertex,
    VertexIter,
    VerticesBuilder,
    VerticesCollection,
)

__all__ = [
    "AdjacentList",
    "BuilderEdge",
    "BuilderVertex",
    "DataType",
    "Edge",
    "EdgeInfo",
    "EdgeIter",
    "EdgesBuilder",
    "EdgesCollection",
    "GraphInfo",
    "Property",
    "PropertyGroup",
    "Vertex",
    "VertexInfo",
    "VertexIter",
    "VerticesBuilder",
    "VerticesCollection",
    "__version__",
]
