# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: GraphAr C++ CI Nightly

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  GraphAr-ubuntu-arrow-from-source:
    runs-on: ubuntu-latest
    env:
      GAR_TEST_DATA: ${{ github.workspace }}/graphar-testing/
    steps:
    - uses: actions/checkout@v4
      with:
          submodules: true

    - name: Cache ccache
      uses: actions/cache@v4
      with:
        path: ~/.ccache
        key: ${{ runner.os }}-nightly-ccache-${{ github.head_ref || github.ref_name }}-${{ github.run_id }}
        restore-keys: |
          ${{ runner.os }}-nightly-ccache-${{ github.head_ref || github.ref_name }}-
          ${{ runner.os }}-nightly-ccache-

    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libboost-graph-dev ccache libcurl4-openssl-dev ninja-build

        # install CMake 3.28+
        wget -O- https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
        echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ jammy main' | sudo tee /etc/apt/sources.list.d/kitware.list >/dev/null
        sudo apt-get update -y
        sudo apt-get install -y cmake

        # install Catch2 v3
        git clone --branch v3.6.0 https://github.com/catchorg/Catch2.git --depth 1
        cmake -B Catch2/build -S Catch2 \
              -DBUILD_TESTING=OFF
        sudo cmake --build Catch2/build \
                   --target install

        git clone https://github.com/apache/incubator-graphar-testing.git $GAR_TEST_DATA --depth 1

    - name: CMake-debug
      run: |
        cmake -B build-debug -S cpp \
              -G Ninja \
              -DCMAKE_BUILD_TYPE=Debug \
              -DBUILD_TESTS=ON \
              -DBUILD_EXAMPLES=ON \
              -DBUILD_ARROW_FROM_SOURCE=ON

    - name: Build GraphAr-debug
      run: |
        ninja -C build-debug
        ninja -C build-debug graphar-ccache-stats
        
    - name: Test-debug
      run: ctest --output-on-failure -C build-debug


    - name: CMake-release
      run: |
        cmake -B build-release -S cpp \
              -G Ninja \
              -DCMAKE_BUILD_TYPE=RelWithDebInfo \
              -DBUILD_TESTS=ON \
              -DBUILD_EXAMPLES=ON \
              -DBUILD_ARROW_FROM_SOURCE=ON

    - name: Build GraphAr-release
      run: |
        ninja -C build-release
        ninja -C build-release graphar-ccache-stats

    - name: Test-release
      run: ctest --output-on-failure -C build-release
